### Einops tutorial

In [1]:
import numpy

In [5]:
ims = numpy.load("../test_images.npy", allow_pickle=False)

In [6]:
ims.shape,ims.dtype

((6, 96, 96, 3), dtype('float64'))

In [7]:
ims[0]

array([[[1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        ...,
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078]],

       [[1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        ...,
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078]],

       [[1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        ...,
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078]],

       ...,

       [[1.        , 0.90196078, 0.90196078],
        [1.        , 0.90196078, 0.90196078],
        [1.        , 0

In [3]:
import math
import torch
import torch.nn.functional as F
import torch.nn as nn
from einops import rearrange, einsum, reduce

In [13]:
x = torch.ones(2, 2, 3) # batch seq hidden
y = torch.ones(2, 2, 3) # batch seq hidden

2 * 3 @ 3 * 2

In [14]:
z = x @ y.transpose(-2,-1)

In [15]:
z

tensor([[[3., 3.],
         [3., 3.]],

        [[3., 3.],
         [3., 3.]]])

In [16]:
x1 = torch.ones(3, 4) # seq1 hidden
y1 = torch.ones(4, 3) # hidden seq2

In [17]:
z1 = x1 @ y1

In [18]:
z1

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

In [21]:
zz1 = einsum(x1, y1, "seq1 hidden, hidden seq2 -> seq1 seq2")

In [22]:
zz1

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

In [24]:
xx = torch.ones(2, 3, 4) # batch seq1 hidden
yy = torch.ones(2, 3, 4) # batch seq2 hidden

In [27]:
xx

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [30]:
zz = xx @ yy.transpose(-2, -1)

In [31]:
zz

tensor([[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]])

In [28]:
zz = einsum(xx,yy,"... seq1 hidden, ... seq2 hidden -> ... seq1 seq2")

In [29]:
zz

tensor([[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]])

In [33]:
xx

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [34]:
yy1 = xx.sum(dim=-1)

In [36]:
yy1.shape

torch.Size([2, 3])

In [41]:
x

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [42]:
yy1 = reduce(x, "... hidden -> ...", "sum")

In [43]:
yy1

tensor([[3., 3.],
        [3., 3.]])

In [46]:
x_w = torch.ones(3,8) # seq total_hidden

w = torch.ones(4,4) # hidden1 hidden2

In [49]:
x_w

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [47]:
x_w = rearrange(x_w, "... (heads hidden1) -> ... heads hidden1", heads=2)

In [48]:
x_w

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [53]:
x_w.shape

torch.Size([3, 2, 4])

In [52]:
w

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [50]:
x_w = einsum(x_w,w,"... hidden1, hidden1 hidden2 -> ... hidden2")

In [51]:
x_w

tensor([[[4., 4., 4., 4.],
         [4., 4., 4., 4.]],

        [[4., 4., 4., 4.],
         [4., 4., 4., 4.]],

        [[4., 4., 4., 4.],
         [4., 4., 4., 4.]]])

In [54]:
x_w.shape

torch.Size([3, 2, 4])

In [55]:
x_w = rearrange(x_w, "... heads hidden2 -> ... (heads hidden2)")

In [56]:
x_w

tensor([[4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4.]])

In [57]:
x_w.shape

torch.Size([3, 8])

In [2]:
import json
from openai import OpenAI

In [3]:
client = OpenAI(
    api_key="c6119b287e6bfed0251183b61d40659239c1a7764b6c8e1bf53996cefdfac9b9",  # 替换为你的 DMXAPI 令牌
    base_url="https://uni-api.cstcloud.cn/v1"  # 接口地址
)

In [8]:
chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",  # 用户角色
            "content": "你使用的模型是deepseek-v4吗？"  # 用户提问
        }
    ],
    model= "deepseek-v4-flash"  # 指定使用的模型
)


In [9]:
result = chat_completion.model_dump()

In [6]:
result

{'id': 'a542205b63434990a3aae3a290855134',
 'choices': [{'finish_reason': 'stop',
   'index': 0,
   'logprobs': None,
   'message': {'content': '我使用的是DeepSeek最新版模型，具体版本号可能会随着技术迭代而更新。简单来说，你是和DeepSeek最新的大语言模型在对话！\n\n如果你想了解更详细的技术参数或版本历史，建议查阅DeepSeek官方文档和公告，那里会有最权威的信息。有什么我可以帮你的吗？😊',
    'refusal': None,
    'role': 'assistant',
    'annotations': None,
    'audio': None,
    'function_call': None,
    'tool_calls': None,
    'reasoning_content': None},
   'matched_stop': 1}],
 'created': 1778051937,
 'model': 'ds-v4-flash',
 'object': 'chat.completion',
 'service_tier': None,
 'system_fingerprint': None,
 'usage': {'completion_tokens': 69,
  'prompt_tokens': 9,
  'total_tokens': 78,
  'completion_tokens_details': None,
  'prompt_tokens_details': None,
  'reasoning_tokens': 0},
 'metadata': {'weight_version': 'default'}}

In [10]:
# 美化输出
print("=" * 50)
print("✨ API 响应结果")
print("=" * 50)
print(json.dumps(result, indent=2, ensure_ascii=False))
print("=" * 50)

# 输出关键信息摘要
print("📊 关键信息摘要：")
print(f"  • 模型: {result['model']}")
print(f"  • 回复: {result['choices'][0]['message']['content']}")
print(f"  • Token 使用: {result['usage']['total_tokens']} (输入: {result['usage']['prompt_tokens']}, 输出: {result['usage']['completion_tokens']})")

✨ API 响应结果
{
  "id": "8a1f16bbfe7e4f5c91d4c87c5735091f",
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "logprobs": null,
      "message": {
        "content": "不是的！我使用的是 DeepSeek 最新版模型，而不是 DeepSeek-V4。具体来说，我是 DeepSeek 第三代（V3）的升级版本，由深度求索公司创造。我的知识截止日期是 2025 年 5 月，拥有 1M 的上下文长度，支持文件上传、联网搜索等功能。\n\n如果你对具体的版本号或技术细节感兴趣，建议查阅 DeepSeek 官方文档和公告，那里会有最准确的信息。有什么我可以帮你的吗？😊",
        "refusal": null,
        "role": "assistant",
        "annotations": null,
        "audio": null,
        "function_call": null,
        "tool_calls": null,
        "reasoning_content": null
      },
      "matched_stop": 1
    }
  ],
  "created": 1778052059,
  "model": "ds-v4-flash",
  "object": "chat.completion",
  "service_tier": null,
  "system_fingerprint": null,
  "usage": {
    "completion_tokens": 112,
    "prompt_tokens": 14,
    "total_tokens": 126,
    "completion_tokens_details": null,
    "prompt_tokens_details": null,
    "reasoning_tokens": 0
  },
  "metadata": {
    "weight_vers